name: Bot scan
on:
  pull_request_target:
    types: [opened, reopened, synchronize, edited]
  issues:
    types: [opened, edited, milestoned] 
permissions:
  issues: write
  pull-requests: write

jobs:
  Snyk_scanning:
    name: Snyk Bot scan
    continue-on-error: true 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Snyk Bot scan
        run: |
          rm -rf node_modules
          rm -f package-lock.json
          npm install
          curl https://static.snyk.io/cli/latest/snyk-linux -o snyk
          chmod +x ./snyk
          mv ./snyk /usr/local/bin/ 
          echo "Downloading and authenticating Snyk CLI..."
          curl -Lo ./snyk "https://github.com/snyk/snyk/releases/download/v1.1100.0/snyk-linux"
          chmod +x snyk
          ./snyk auth ${{ secrets.SNYK_TOKEN }}
          echo "Running Snyk test and monitor..."
          ./snyk test --all-projects --color --json || true
          ./snyk monitor --all-projects || true

  TruffleHog_scanning:
    name: TruffleHog Bot scan
    continue-on-error: true 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install TruffleHog using pip
        continue-on-error: true 
        run: |
          pip install truffleHog

      - name: Run TruffleHog Scan (pip)
        continue-on-error: true 
        run: |
          trufflehog --regex --entropy=False ${{ github.event.pull_request.head.repo.clone_url }} --json
 
  BotCheck:
    name: Bot scan 
    continue-on-error: true 
    permissions: write-all
    runs-on: ubuntu-latest
    needs: [Snyk_scanning, TruffleHog_scanning]
    steps:
      - uses: itsarraj/pr-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

